function y = Elliptic(x)
%ELLIPTIC Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 02-Feb-2020 13:19:04

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N      = 4;    % Order
    % Fpass1 = 49;   % First Passband Frequency
    % Fpass2 = 51;   % Second Passband Frequency
    % Apass  = 1;    % Passband Ripple (dB)
    % Astop  = 60;   % Stopband Attenuation (dB)
    % Fs     = 360;  % Sampling Frequency
    %
    % h = fdesign.bandstop('n,fp1,fp2,ap,ast', N, Fpass1, Fpass2, Apass, ...
    %                      Astop, Fs);
    %
    % Hd = design(h, 'ellip', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.28491783053537 1 1 -1.25279886307543 ...
        0.982589075273413; 1 -1.28662346957407 1 1 -1.29611003429387 ...
        0.982994896889564], ...
        'ScaleValues', [0.935844315781992; 0.935844315781992; 1]);
end

y = step(Hd,x);


